// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evivgpakwpfuqmdkrpam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2aXZncGFrd3BmdXFtZGtycGFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2OTUzNDEsImV4cCI6MjA1ODI3MTM0MX0.2Z3M5KyeCT-KnJu_B6Pzi3CebDu6JO7NzFkjyWeJGWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);